CHANGELOG.md, Cargo.toml, README.md, src/lib.rs
- Added `TlsLoader` to reload tls configuration.
- Added `Handle` to provide additional utilities for server.
=> Version 0.2.0

CHANGELOG.md, Cargo.toml
- Fixed `serve_and_record` not recording independently for each connection.
=> Version 0.2.1

src/server/http_server.rs, src/server/mod.rs, src/server/socket_addrs.rs, src/server/tls.rs
=> Fix bind address implementation

Cargo.toml
Motivation: https://github.com/tokio-rs/axum/pull/173
=> Reduce futures-util features

CHANGELOG.md, Cargo.toml
- Reduced `futures-util` features to improve compile times.
=> Version 0.2.4

src/util/traits.rs
:)
```
❯ cargo +1.51 check --all-features --tests
Finished dev [unoptimized + debuginfo] target(s) in 0.06s
```
Encountered the exact some issue [in tonic](https://github.com/hyperium/tonic/pull/669) a while ago.
=> Fix compilation on rust 1.51

CHANGELOG.md, Cargo.toml
=> Version 0.2.5

CHANGELOG.md, Cargo.toml
- **added:** Added `HttpConfig` to allow more configuration.
=> Version 0.3.2

Cargo.toml, src/addr_incoming_config.rs, src/handle.rs, src/server.rs, src/tls_rustls/mod.rs
=> Make Handle::listening return option

Cargo.toml, src/tls_rustls/mod.rs
=> Support EC Keys

CHANGELOG.md
- **added:** Added `map`, `get` and `get_mut` methods to access the acceptor
of `Server`.
=> Version 0.4.1

CHANGELOG.md, Cargo.toml
- **added:** Added `tcp_keepalive_interval` and `tcp_keepalive_retries` to
`AddrIncomingConfig`.
=> Version 0.4.3

Cargo.toml, src/handle.rs, src/tls_rustls/mod.rs
=> Documentation improvements

CHANGELOG.md, Cargo.toml
- **added:** Openssl is now supported.
=> Version 0.4.7

examples/multiple_addresses.rs
=> Add multiple_addresses example

src/tls_rustls/mod.rs
=> Support PEM file where key is not at top for rustls config

Cargo.toml, src/tls_rustls/mod.rs
=> fix: rustls 0.22 issues

src/server.rs
The hyper v1 migration PR (#93) accidentally (?) removed the call to `serve_future.graceful_shutdown()`, which prevents the server from shutting down until all client _connections_ close on their own (or we hit the hard shutdown timeout).
In practice, this meant we always hit the hard shutdown timeout, since most clients use connection pools with connection keepalive.
With this change, graceful shutdown will now correctly stop handling any new requests after it's triggered, while letting existing requests complete (within the timeout of course).
The fix itself is just one line:
```diff
let serve_future = builder.serve_connection_with_upgrades(io, service);
tokio::pin!(serve_future);
tokio::select! {
biased;
_ = watcher.wait_graceful_shutdown() => {
+ …
```
=> fix: propagate graceful shutdown to inner hyper connection

.github/workflows/ci.yml, src/lib.rs
This adds checking [Rustdoc lints](https://doc.rust-lang.org/1.80.0/rustdoc/lints.html) in the CI.
=> Lint Documentation

.github/workflows/ci.yml, Cargo.toml, README.md
This build the crate in CI on stable and its MSRV.
I also corrected the MSRV in the README and encoded it in `Cargo.toml`.
=> Build in CI

.github/workflows/ci.yml
=> Run `cargo-audit` in CI

.github/dependabot.yaml
=> Setup Dependabot

Cargo.toml, src/server.rs, src/service.rs
Uses upstream `hyper_util::service::TowerToHyperService`.
=> Use upstream hyper_util::service::TowerToHyperService

Cargo.toml, src/server.rs
=> Refactor dependencies
