CHANGELOG.md
Fixed an import issue when using `tls-rustls` feature.
=> Version 0.1.2

CHANGELOG.md, Cargo.toml
Fixed #13.
- Added uri `Scheme` in `Request` extensions.
- Fixed memory leak that happens as connections are accepted.
=> Version 0.2.2

CHANGELOG.md, Cargo.toml
- Fixed `bind` and `bind_rustls` not working on some types.
=> Version 0.2.3

CHANGELOG.md, Cargo.toml
- **Total rewrite of source code.**
- **Major api changes:**
- **breaking:** Removed `bind_rustls`, `certificate`, `certificate_file`,
`loader`, `new`, `private_key`, `private_key_file`, `serve_and_record`,
`tls_config` methods from `Server`.
- **breaking:** Removed `tls` module.
- **breaking:** Removed `record` module and feature.
- **breaking:** Removed `Handle::listening_addrs` method.
- **breaking:** `Server::bind` method doesn't take `self` anymore and creates
an `Server`.
- **breaking:** `bind` method now takes a `SocketAddr`.
- **breaking:** `bind_rustls` method now takes a `SocketAddr` and an
`tls_rustls::RustlsConfig`.
- **breaking:** `Server::serve` method now takes a `MakeService`.
- **breaking:** `Handle::listening` method now returns `SocketAddr`.
- **added:** Added …
=> Version 0.3.0

src/http_config.rs, src/lib.rs, src/server.rs
This PR adds a new trait to allow the created `Http` to be configured.
=> feat: add the ability to configure `Http` values

examples/configure_addr_incoming.rs, src/addr_incoming_config.rs, src/lib.rs, src/server.rs
This PR exposes three additional server settings, which are normally found here: https://docs.rs/hyper/latest/hyper/server/struct.Builder.html#impl-1
- TCP keepalive duration
- TCP nodelay boolean
- TCP sleep on accept errors boolean
All method names and defaults match the upstream builder.
Let me know if you want any changes!
=> Add AddrIncomingConfig

CHANGELOG.md
- Added TLS handshake timeout(10 seconds).
- In `RustlsConfig`: `from_pem` and `from_pem_file` methods now accept EC
keys.
- **added:** Added `AddrIncomingConfig` to allow configuration of
`hyper::server::conn::AddrIncoming`.
- **added:** Added `HttpConfig::http1_header_read_timeout`.
- **breaking:** Changed `Handle::listening` return type to
`Option<SocketAddr>`. If binding fails, `Option::None` will be returned.
=> Version 0.4.0

src/server.rs
- `Server::map()`: maps the acceptor, consuming.
- `Server::get_ref()`: gets a reference to the acceptor.
- `Server::get_mut()`: gets a mutable reference to the acceptor.
Bikeshedding welcome.
Fixes #49.
=> Add methods to work with the acceptor in `Server`

CHANGELOG.md, Cargo.toml
- **added:** Added `Server::from_tcp`, `axum_server::from_tcp` and
`axum_server::from_tcp_rustls` methods to create `Server` from
`std::net::TcpListener`.
=> Version 0.4.2

src/handle.rs, src/server.rs
Currently, on a graceful shutdown, connections are not informed, however for streaming or long-lived connections, it can be valuable to inform the connections that we wish them to shut down. Currently, with an open HTTP/2 channel, the graceful shutdown mechanism does not cause the server to begin winding down the connection, instead waiting until the graceful termination timeout elapses before killing the whole server.
With this change, on a graceful shutdown signal, the connection will be notified, and then it will return to waiting for either the connection to self-terminate or the termination timeout. On HTTP/2, this allows it to send the appropriate GOAWAY frame when the connection has processed all pending requests.
This also has the benefit of terminating keep-alive probes for …
=> feat: inform connections on a graceful shutdown request

CHANGELOG.md, Cargo.toml
- **changed:** `Handle::graceful_shutdown` now informs connections about the
graceful shutdown.
=> Version 0.4.5

Cargo.toml, src/lib.rs, src/tls_openssl/future.rs, src/tls_openssl/mod.rs
Fixes #69 - Add support for openssl in this crate.
This is currently a WIP - next I need to clean up the code, improve the acceptor builder, and then write the docs. Putting in the draft now to show the basic elements. Mostly this was modeled on the rustls code, but with the changes needed due to the differences in the OpenSSL tokio bindings.
=> 20230309 add openssl feature

Cargo.toml, examples/rustls_session.rs
I did run `cargo test --features tls-rustls`, everything seems to work just fine.
This is a breaking change because we expose some `rustls` types.
=> [breaking change] Update `rustls` to v0.21

CHANGELOG.md, Cargo.toml
- **breaking:** Updated `rustls` from `0.20` to `0.21` which affects
`ServerConfig` type.
- **breaking:** Updated `tokio-rustls` from `0.23` to `0.24` which affects
`TlsStream` type.
=> Version 0.5.0

CHANGELOG.md, Cargo.toml
- **added:** `http2_enable_connect_protocol`, `http2_max_header_list_size`,
`http2_max_pending_accept_reset_streams` and `http2_max_send_buf_size`
methods to `HttpConfig`.
=> Version 0.5.1

Cargo.toml
Currently `axum-server` doesn't compile when used as a dependency because it is missing some features in `hyper-util`. This was probably covered up by `dev-dependencies`.
=> Fix compilation as a dependency

Cargo.toml, src/accept.rs, src/server.rs, src/tls_rustls/mod.rs
Output from cargo fix and cargo test
```
$ cargo fix --edition
note: Switching to Edition 2021 will enable the use of the version 2 feature resolver in Cargo.
This may cause some dependencies to be built with fewer features enabled than previously.
More information about the resolver changes may be found at https://doc.rust-lang.org/nightly/edition-guide/rust-2021/default-cargo-resolver.html
When building the following dependencies, the given features will no longer be used:
futures-channel v0.3.28 removed features: futures-sink, sink
futures-task v0.3.28 removed features: std
futures-util v0.3.28 removed features: channel, futures-channel, futures-io, futures-sink, io, memchr, sink, slab, std
hyper v1.0.1 removed features: client, full
tokio v1.32.0 removed features: fs, full, num_cpus, …
```
=> Update rust edition, clean up linter warnings, format code

README.md
Hyper's current MSRV is 1.63 and since that is a requirement we have to raise the crate's MSRV
=> Update MSRV on README

src/server.rs
Unlike `std::net::TcpListener`, `tokio::net::TcpListener` will internally accept TCP connections even when the application has stopped calling accept on the `TcpListener`. As such, connection attempts during a graceful shutdown will be accepted by tokio, but will not be processed; once the shutdown completes, the connections will be closed.
This PR drops the `TcpListener` before waiting for the shutdown to complete, so that new connection attempts during a shutdown are immediately refused, rather than them being accepted and then hanging until the shutdown completes.
=> Refuse new connections during graceful shutdown

CHANGELOG.md, Cargo.toml, src/tls_rustls/mod.rs
- **changed**: Updated `rustls` from `0.21` to `0.23`.
- **changed**: Updated `tokio-rustls` from `0.24` to `0.26`.
- **changed**: Updated `hyper` from `1.0.1` to `1.4`.
- **changed**: Updated `http` from `1.0.0` to `1.1`.
- **added**: `rustls-pki-types` dependency for the `tls-rustls` feature.
- **changed**: Replaced usage of `rustls::Certificate` and `rustls::PrivateKey` with `rustls_pki_types::CertificateDer` and `rustls_pki_types::PrivateKeyDer`.
- **changed**: Updated `ServerConfig` initialization to remove `with_safe_defaults()` call.
- **changed**: Updated `ClientConfig` initialization in tests to use `dangerous()` instead of `with_safe_defaults()`.
- **changed**: Updated `ServerCertVerifier` implementation in tests to match new rustls API.
- **changed**: Minor version bumps for …
=> upgrade hyper, http and rustls

CHANGELOG.md, Cargo.toml
- **fixed**: Graceful shutdown now stops accepting requests from existing connections.
- **changed**: Updated `rustls` from `0.21` to `0.23`.
- **changed**: Updated `tokio-rustls` from `0.24` to `0.26`.
- **changed**: Updated `hyper` from `1.0.1` to `1.4`.
- **changed**: Updated `http` from `1.0.0` to `1.1`.
- **added**: `rustls-pki-types` dependency for the `tls-rustls` feature.
- **changed**: Replaced usage of `rustls::Certificate` and `rustls::PrivateKey` with `rustls_pki_types::CertificateDer` and `rustls_pki_types::PrivateKeyDer`.
- **changed**: Updated `ServerConfig` initialization to remove `with_safe_defaults()` call.
- **changed**: Updated `ClientConfig` initialization in tests to use `dangerous()` instead of `with_safe_defaults()`.
- **changed**: Updated `ServerCertVerifier` …
=> Version 0.7

Cargo.toml, src/lib.rs
I copied the idea from [`reqwest`](https://github.com/seanmonstar/reqwest/blob/29d4cff234b37065632512f002b9785700c51aa8/Cargo.toml#L43-L44), let me know if this is to your liking as well.
I left any `doc(cfg(feature = "tls-rustls")))` in place because `tls-rustls-no-provider` is really long.
Fixes #126.
=> Add `tls-rust-no-provider` crate feature

Cargo.toml
`axum-server` actually requires `hyper-util` v0.1.2, its will fail to compile with earlier versions.
This was set correctly before, but was accidentally removed in #124.
Before that the requirement was raised from `v0.1.1` to `v0.1.2` by #119.
=> Fix minimal required version of `hyper-util`

CHANGELOG.md, Cargo.toml
Prepare a new v0.7.1 release.
- **added**: Crate feature `tls-rustls-no-provider`, which enables no `rustls::crypto::CryptoProvider`.
- **fixed**: Correct minimum required `hyper-util` to `0.1.2`.
=> Version 0.7.1

.github/workflows/ci.yml, minimal-versions/.gitignore, minimal-versions/Cargo.toml, minimal-versions/src/lib.rs
This uses the [`-Zminimal-versions`](https://doc.rust-lang.org/1.80.0/cargo/reference/unstable.html#minimal-versions) argument to test minimal dependency versions in CI.
To avoid minimal dependency versions that aren't reflected in a user build, we have to avoid using a `Cargo.toml` with dev-dependencies. So unfortunately creating a dedicated testing crate just for this test was needed.
=> Test minimal dependency versions in CI

.github/dependabot.yaml
[`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain) doesn't use regular versioning, instead it uses its version to signify the Rust toolchain version.
I can't really test Dependabot other then merging it, unfortunately.
So hopefully this is correct.
See #138.
=> Disable checking `dtolnay/rust-toolchain`

CHANGELOG.md, src/tls_rustls/mod.rs
Fixes #142 - allows usage of EC and PKCS1 keys.
=> 20240818 ec crypto

.github/workflows/ci.yml
Latest `tokio-util` has updated its MSRV to v1.70, but we are still on v1.66.
=> Fix MSRV CI

Cargo.toml, src/tls_rustls/mod.rs
[fs-err](https://crates.io/crates/fs-err) adds information about why the file failed to load as well as the filename. This information was otherwise discarded, which makes diagnosing any failures require code.
=> Use fs-err to augment errors loading pem files

CHANGELOG.md, Cargo.toml
- **changed**: Use fs-err to augment errors loading pem files.
- **changed**: Updated `tower` from `0.4` to `0.5`.
- **added**: Support reading PKCS\#1 and SEC1 private keys with Rustls.
=> Version 0.7.2
